### ISSUE TITLE
Application debug symbols can't be loaded (unsupported format)

### ISSUE THREAD

**Issue by skrysmanski** [Azure/service-fabric-aspnetcore#17] opened 2017-05-22 15:46 UTC
Visual Studio 2017 can't load the debug symbols of a freshly created ASP.NET Core Service Fabric application.

## Steps To reproduce:

1. Open new VS 2017 instance
1. Create new project of type "Service Fabric Application" (under "Visual C#" -> "Cloud"). 
  The selected target framework doesn't seem to matter here.
1. In the following dialog ("New Service Fabric Service") select "ASP.NET Core" and hit Ok.
   I've also tried "Stateless Service" which works fine btw.
1. In the next dialog select "Empty" (and keep ASP.NET Core 1.1) in the next dialog and hit again "Ok".
  Actually, it doesn't matter what type you select.
1. In the newly created project, open up any .cs file and add a breakpoint.
1. Start solution with "Start Debugging" (F5).

Notice how the breakpoint in the sidebar is not filled. Hovering over it says that "no symbols have been loaded".

![breakpoint](https://cloud.githubusercontent.com/assets/914747/26316209/c5e7e770-3f13-11e7-89eb-ddfdbbb94fa8.png)

## More details
When pausing the application/debugger and going to the main thread, Visual Studio will state that the "PDB format is not supported".

![pdb-format-not-supported](https://cloud.githubusercontent.com/assets/914747/26316379/5d11209e-3f14-11e7-9369-17bb7e5ecd0e.png)

Opening the project properties of the web project and then going to *Build* -> *Output* -> *Advanced* shows under *Debugging information* that *portable* is selected.

Running the web project *directly* with this option selected also results in the "PDB format is not supported" problem. 

When switching to *full*, breakpoints work when running the web project *directly*.

However, when running in Service Fabric, breakpoints still don't work (despite of having selected "full").

## Versions
I'm running Visual Studio 2017 with the latest update (15.2 26430.6).

I'm not sure where to look up the installed/used versions of .NET Core, ASP.NET Core, or Service Fabric but I'll update this issue if anyone tells me where to find them and if they're important.

**Comment by karolz-ms** [comment] 2017-05-22 19:16
Does "Rebuild solution" before F5 help?

**Comment by skrysmanski** [comment] 2017-05-23 05:55
@karolz-ms Nope, rebuilding doesn't help.

**Comment by vturecek** [comment] 2017-05-24 00:59
@skrysmanski Can you add your Service Fabric versions and .NET Core versions? Go into Programs and Features and look for:
 - .NET Core SDK
 - Microsoft Azure Service Fabric
 - Microsoft Azure Service Fabric SDK

I have VS 2017 v15.2 installed and can't repro this. @MikkelHegn any ideas?

**Comment by skrysmanski** [comment] 2017-05-24 05:44
For .NET Core I see this under Programs and Features:

![dotnetcore](https://cloud.githubusercontent.com/assets/914747/26388436/9dc7400a-4054-11e7-94f7-77e587d79ea7.png)

For Service Fabric, it shows this:

![servicefabric](https://cloud.githubusercontent.com/assets/914747/26388469/c1482792-4054-11e7-9932-7a745462efe1.png)

**Comment by skrysmanski** [comment] 2017-05-24 06:52
Today, I saw that there's a new Service Fabric version, so I upgraded to 5.6./2.6. but it didn't help. I even recreated the project but this also didn't fix the problem.

**Comment by vturecek** [comment] 2017-05-25 20:32
Pretty weird, I can't repro this at all. Usually when you see this it means the debugger is not attached to the EXE that the file is in. Are you running Visual Studio as administrator? Can you go into the debug menu to see if the debugger is getting attached to your service EXE?

And one more thing that might help us figure this out: can you right-click the SF Application project, go to properties, and tell me what you have set for Application Debug Mode?

**Comment by skrysmanski** [comment] 2017-05-29 06:51
I've create a GitHub repo with which I can reproduce the problem:

https://github.com/skrysmanski/bugs-service-fabric-asp-net-core-debug-symbols

Maybe this can help you figure out what's wrong here.

> Are you running Visual Studio as administrator?

Yes, although I think this should not affect the problem.

> Can you go into the debug menu to see if the debugger is getting attached to your service EXE?

According to the "Threads" view I'm attached to the correct process:

![attached](https://cloud.githubusercontent.com/assets/914747/26539246/aa8ea9cc-444b-11e7-84ae-48b88cd285a9.png)

> tell me what you have set for Application Debug Mode?

Application Debug Mode is set to "Remove Application".

While being in the SF application's properties dialog, I noticed that under "Debugging" it says "Unsupported debug option"; maybe this is related to the problem?

![unsupported](https://cloud.githubusercontent.com/assets/914747/26539284/e749badc-444b-11e7-9f83-47ceb298e87e.png)

**Comment by karolz-ms** [comment] 2017-05-30 22:46
@skrysmanski I am puzzled about this. Can't reproduce the problem either using the solution you posted to GitHub. The only thing I had to change to hit the breakpoint was the active solution platform (from "AnyCPU" to "x64"), please verify that you have done (Build menu | Configuration Manager | Active Solution Platform).

The "unsupported debug option" is kind-of expected, it just indicates that the standard VS properties dialog does not understand how SF project orchestrates the debugging session.

**Comment by skrysmanski** [comment] 2017-05-31 06:21
@karolz-ms I've removed the "Any CPU" solution configuration to avoid confusion. I have always been using the "x64" configuration and can still reproduce it.

In the meantime I've also tried the following things (but *none of them fixed the problem*):
* I've updated Visual Studio to version 15.2 26430.12 (out today).
  * With the new version, I've created a new ASP.NET Core Stateless service project from scratch to see if the new template fixes the problem.
* In the VS options, under Debugging -> Symbols, I've selected "All modules, unless excluded". (I usually have "Only specified modules" selected.)

**Comment by skrysmanski** [comment] 2017-05-31 08:19
More findings:
* When I just build the web project, create the SF package manually and then publish it via PowerShell, the PDB files work fine (i.e. breakpoints work fine after attaching the debugger manually).
* When I publish/run the SF project through VS, the process for some reasons creates a *second* output folder in the web project's `bin` directory. 
  * When I just build the solution, I get a `bin\Debug` folder. 
  * When I publish the solution, I get an additional `bin\x64\Debug` folder.
  * Setting the output folder of the web project manually to ` bin\x64\Debug` doesn't solve the problem, though.

**Comment by skrysmanski** [comment] 2017-05-31 09:55
I think I've found out what's the problem here (although I haven't found any solution yet).

The problem consists actually of two problems:
1. My Visual Studio 2017 debugger doesn't support portable PDBs.
1. When packaging a Service Fabric project, Visual Studio ignores the project settings of ASP.NET projects. It thus compiles the web project with portable PDBs rather than "full" PDBs.

The first point is easily observable (at least on my computer) by switching the PDB format to portable in the Web1 project settings and then starting the Web1 project directly. In this situation, I get the same "PDB format not supported" message and no breakpoint hits. I tried to google this problem but couldn't find anything on this. Are there any requirements necessary to debug portable PDBs?

The second point can be observed by first cleaning the `Web1\bin` directory and then packaging the Service Fabric project directly in VS. Now, in the `Web1\bin` directory there are two output folders (like described in my previous comment). This seems to be caused by Visual Studio ignoring the `$(OutputPath)` setting of the `Web1` project when *packaging* the Service Fabric project. For that same reason, Visual Studio compiles the project with portable PDBs (as this seems to be the default for the project type) rather than full PDBs.

I'd argue that the second point is a bug while the first point is either a bug or just poor error feedback (i.e. could be "fixed" by improving the error message shown).

**Comment by skrysmanski** [comment] 2017-06-01 06:43
So, the first problem has been solved via StackOverflow. Thus, only problem 2 remains which should be fixed, IMO.

**Comment by MikkelHegn** [comment] 2017-06-01 16:22
We will fix honoring the pdb type, hence "bugging" this issue.

**Comment by skrysmanski** [comment] 2017-06-06 05:58
@MikkelHegn Just FYI: It's not just the pdb type. It's also the output directory that gets ignored - and maybe there are other settings that get ignored as well.

**Comment by dbreshears** [comment] 2017-11-22 22:05
@skrysmanski.   I believe these issues are fixed in the latest VS 2017 tooling with services using .Net Core 2.0. I tried to repro just now but couldn't.   Please re-open if you find this is not the case.

**Closed by dbreshears** 2017-11-22 22:05 UTC
Labels: bug

**Comment by cfahrenholz** [comment] 2018-03-01 12:34
I had a similar problem when I was not able to debug my .Net Standard 2.0 library. I had to disable "Use Managed Compatibility Mode" under VS Tools -> Options -> Debugging -> General.
