### ISSUE TITLE
Error Code 3221225786

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric-aspnetcore#30] opened 2017-09-14 19:05 UTC
ServiceFabric v5.7.198.9494 - 3 node cluster running AspNetCore 2.0 Kestrel MVC site
giving Error Code 3221225786 however the site works fine on single node dev box localhost ?

**Comment by amanbha** [comment] 2017-09-14 20:05
Is the 3 node cluster is on one box or on 3 machines? Could you please share Service Fabric traces for the cluster, if its in Azure, please share the resource id of the cluster.

**Comment by grahamehorner** [comment] 2017-09-14 21:14
The cluster is running on virtual machines on a single physical server, each virtual machine has been allocated 4 cores 16gb memory with 60gb storage and is running Windows Server 2016 standard core

**Comment by amanbha** [comment] 2017-09-14 21:26
Oh ok, its an on-premise cluster, could you share the cluster traces as well.

**Comment by grahamehorner** [comment] 2017-09-14 21:29
@amanbha I will do in morning GMT when back in the office

**Comment by TonyHenrique** [comment] 2017-09-23 21:07
I also had some problems, like crashes, with Azure Service Fabric installed on my Windows 10 x64. Where can I get the logs to send to you?

**Comment by amanbha** [comment] 2017-09-23 21:14
@TonyHenrique  if these are not for AspNetCore, please open issue on our main Service Fabric issue at https://github.com/Azure/service-fabric-issues. If its a one box cluster, the logs would be at C:\sfdevcluster\log\traces (if you didn't change the value of ClusterLogRoot for local cluster creation). Also want to mention that Win10 environment is for dev purpose only, its not for production.

**Comment by TonyHenrique** [comment] 2017-09-23 21:42
OK, I am new to this, but on my first clicks, something appear to have crashed.

I did not even put any of my service on it, 
I just installed it, then entered on this url

http://localhost:19080/Explorer/index.html#/node/_Node_0

then clicked
Deactivate (Pause),
Deactivate (Restart),
Restart

in sequence, quickly.

See logs: 
Traces.zip
https://drive.google.com/open?id=0B5d9oJc6UeFKYTdheUpqUlY5d2s

**Comment by grahamehorner** [comment] 2017-09-23 23:13
Sorry it's taken a while to reply, been busy rebuilding our hyper-v servers with more memory and installation of service fabric on a fresh windows server 2016 standard  non-desktop experience, the hyper-v nodes'(3 of) have 128gb of ram with 1tb raid 50 disk space each with 2 * 8 core 2.5ghz cpu

I've deployed a 7 node service fabric cluster across these 3 hosts each service fabric node has been assigned 2 virtual cpu and 16gb of memory with two vhdx one 40gb and one 120gb the is is located on the 40gb while ServiceFabric is making use of the 120gb

I will be deploying the code (unchanged) to these nodes in the next few days to see if this problem persists, either way I will give an update once this is completed

**Comment by amanbha** [comment] 2017-09-24 00:46
@TonyHenrique let's not do that without understanding the implications. How many nodes cluster was it? Could you explain what crashed? You can recreate the cluster and it should work for you .

**Comment by grahamehorner** [comment] 2017-09-24 17:01
The original cluster is still configured, with 3 nodes the cluster wouldn't/couldn't even start a simple aspnetcore stateless webapi service?

**Comment by grahamehorner** [comment] 2017-10-03 07:14
This seems to be a resource issue on the ServiceFabric virtual machines, when increase available resources CPU, memory the application started as expected; I then started to reduce resource to a point where the application failed to start in a timely manor and reproduced the issues.

**Comment by amanbha** [comment] 2017-10-03 15:56
@grahamehorner  Thanks for confirming the root cause of the issue. Closing this for now,  If you have any questions, please feel free to reopen this or create a new issue.

**Closed by amanbha** 2017-10-03 15:56 UTC
