### ISSUE TITLE
Unable to deploy aspnetcore stateful service

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-aspnetcore#40] opened 2017-11-17 09:54 UTC
Dear team, what happens with statefull services - I cannot deploy none of them.
I've created sample projects for aspnetcore1.0, aspnetcore1.1 and aspnetcore 2.0 and none of them cannot be deployed seccessfully. At the same time stateless service works fine.

I've just created sample application from template "Stateful ASP.Net Core" with web api service targeted to aspnetcore1.1, update servicefabric packages to the latest versions an try to debug the service.
Exceptions:
`
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
`

Repository with sample you can [find here](https://github.com/mgrishkov/sf-statefull-web-api).
Here you can find [Build](https://github.com/mgrishkov/sf-statefull-web-api/blob/master/logs/build.log), [Debug](https://github.com/mgrishkov/sf-statefull-web-api/blob/master/logs/debug.log) and [Service Fabric Tools logs](https://github.com/mgrishkov/sf-statefull-web-api/blob/master/logs/service-fabric-tools.log).

I found issue #36 and it seems to be fixed, but I don't understand how to solve my issue. Does it connected somehow with my [issue in the service-fabric thread](https://github.com/Azure/service-fabric-issues/issues/627)?

P.S. I've also tried to deploy standard net462 stateful service and connect to it via remoting, but I get the same COM exception.

Sistem information:
```
Win10.
ServiceFabric local cluster: 6.0.232.9494
ServiceFabric SDK: 2.8.232.9494

```

**Comment by amanbha** [comment] 2017-11-17 16:17
Is this with services built for netcore only or with full .net as well.This issue doesn't seem to be specific to aspnetcore,  it could be related to your other issue https://github.com/Azure/service-fabric-issues/issues/627
@raunakpandya @hrushib

**Comment by hrushib** [comment] 2017-11-23 09:35
Duplicate of Azure/service-fabric-issues#639.

**Closed as completed by hrushib** 2017-11-23 09:35 UTC
Labels: investigating
